package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    JoinPredicate p;
    DbIterator child1, child2;
    Tuple t1, t2;
    
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        // some code goes here
        this.p = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // some code goes here
        return this.p;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // some code goes here
        return this.child1.getTupleDesc().getFieldName(p.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // some code goes here
        return this.child2.getTupleDesc().getFieldName(p.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // some code goes here
        super.open();
        child1.open();
        child2.open();
    }

    public void close() {
        // some code goes here
        super.close();
        child1.close();
        child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // some code goes here
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // some code goes here
        if(child1.hasNext() && t1 == null) t1 = child1.next();
        while(t1 != null){
            while(child2.hasNext()){
                t2 = child2.next();
                
                  
                if(p.filter(t1, t2)){
         /*           System.out.printf("t1:%d\n", t1.getTupleDesc().numFields());
                for(int i = 0; i < t1.getTupleDesc().numFields(); i++)
                  System.out.printf("%d ", Integer.parseInt(t1.getField(i).toString()));
                System.out.println("x");

                System.out.printf("t2:%d\n", t2.getTupleDesc().numFields());
                for(int i = 0; i < t2.getTupleDesc().numFields(); i++)
                  System.out.printf("%d ", Integer.parseInt(t2.getField(i).toString()));
                System.out.println("x");*/

                    Tuple res = new Tuple(TupleDesc.merge(t1.getTupleDesc(), t2.getTupleDesc()));
                    for(int i = 0; i < t1.getTupleDesc().numFields(); i++)
                      res.setField(i, t1.getField(i));
                    for(int i = t1.getTupleDesc().numFields(); i < res.getTupleDesc().numFields(); i++)
                      res.setField(i, t2.getField(i - t1.getTupleDesc().numFields()));
                    


            /*        System.out.printf("res:%d\n", res.getTupleDesc().numFields());
                    for(int i = 0; i < res.getTupleDesc().numFields(); i++)
                      System.out.printf("%d ", Integer.parseInt(res.getField(i).toString()));
                    System.out.println("x");
            */       return res;
                }
            }
            if(child1.hasNext()) t1 = child1.next();
            else t1 = null;
            child2.rewind();
        }
          
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        // some code goes here
        return new DbIterator[] {child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        // some code goes here
        if(children.length < 2) return ;
        children[0] = child1;
        children[1] = child2;
    }

}
